#!/bin/bash

case $1 in
  start)
    echo "This initscript does not support the 'start' parameter."
    exit 3
  ;;
  stop)
    for dreamhack in `/dreamhack/lib/bin/all-home-dirs`; do
      if [ -f "$dreamhack/apache/etc/httpd.pid" ]; then
        echo "Stopping Dreamhack at $dreamhack..."
        DREAMHACK_DIR="$dreamhack"
        export DREAMHACK_DIR
        /usr/sbin/apache2ctl -f /dreamhack/etc/apache/safe-stop.conf -k stop   # uses $DREAMHACK_DIR to know which Apache to stop
        sleep 1
      fi
    done
  ;;
  *)
    echo "Usage: $0 stop"
    exit 3
  ;;
esac
